/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Modelo.materias;
import controlador.conexion;
import controlador.control_materias;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Yessica_Alexandra_Conejo_Munoz
 */
public class Crud_materias extends javax.swing.JPanel {
    
    control_materias cm =  new control_materias();
    materias m = new materias();
    private List<materias> materias;
    int cod_mat=0;
    /**
     * Creates new form Crud_notas
     */
    public Crud_materias() {
        initComponents();
       
        this.llenar_tabla();
        this.llenar_combobox();
    }
    
    
    public void llenar_tabla() {
        try {
            materias = cm.recuperarTodas(conexion.obtener());
            DefaultTableModel tmm = (DefaultTableModel) t_materias.getModel();
            tmm.setRowCount(0);
            for (int i = 0; i < materias.size(); i++) {
                tmm.addRow(new Object[]{
                    this.materias.get(i).getId(),
                    this.materias.get(i).getNombre(),
                    this.materias.get(i).getGrado()

                });
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "No se Obtuvieron registros ...");
        }

    }

    public void llenar_combobox() {
        String[] grados = {"Ninguno","Segundo", "Tercero", "Cuarto", "Quinto", "Sexto", "Septimo", "Octavo", "Noveno", "Decimo", "Once"};

        for (String grado : grados) {
            this.Lista_grados.addItem(grado);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_materias = new javax.swing.JTable();
        Formulario_mat = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        caja_cod = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        caja_nombre = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        Lista_grados = new javax.swing.JComboBox<>();
        jSeparator3 = new javax.swing.JSeparator();
        btn_agregar = new javax.swing.JButton();
        btn_actualizar = new javax.swing.JButton();
        btn_borrar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Roboto Slab Medium", 0, 18)); // NOI18N
        jLabel1.setText("Materias");

        t_materias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Grado"
            }
        ));
        t_materias.setGridColor(new java.awt.Color(255, 255, 255));
        t_materias.setSelectionBackground(new java.awt.Color(1, 204, 201));
        t_materias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_materiasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(t_materias);

        Formulario_mat.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Codigo:");

        caja_cod.setBorder(null);
        caja_cod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja_codActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombre:");

        caja_nombre.setBorder(null);

        jLabel4.setText("Grado:");

        Lista_grados.setBorder(null);

        javax.swing.GroupLayout Formulario_matLayout = new javax.swing.GroupLayout(Formulario_mat);
        Formulario_mat.setLayout(Formulario_matLayout);
        Formulario_matLayout.setHorizontalGroup(
            Formulario_matLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Formulario_matLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Formulario_matLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(caja_cod, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(caja_nombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(Formulario_matLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(Formulario_matLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(Formulario_matLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lista_grados, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Formulario_matLayout.setVerticalGroup(
            Formulario_matLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Formulario_matLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(Formulario_matLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Formulario_matLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(caja_cod)
                    .addComponent(Lista_grados, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Formulario_matLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 10, Short.MAX_VALUE)
                    .addComponent(jSeparator1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(caja_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        btn_agregar.setText("agregar");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });

        btn_actualizar.setText("Actualizar");
        btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarActionPerformed(evt);
            }
        });

        btn_borrar.setText("Eliminar");
        btn_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_borrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(328, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(17, 17, 17))
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(btn_agregar)
                .addGap(18, 18, 18)
                .addComponent(btn_actualizar)
                .addGap(18, 18, 18)
                .addComponent(btn_borrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Formulario_mat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(Formulario_mat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_agregar)
                    .addComponent(btn_actualizar)
                    .addComponent(btn_borrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void caja_codActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja_codActionPerformed

    }//GEN-LAST:event_caja_codActionPerformed

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        if (this.validar()) {
            this.guardar();
            this.limpiar_cajas();
            this.llenar_tabla();
            
        }
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void btn_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_borrarActionPerformed
        try {
            cm.Eliminar(conexion.obtener(), cod_mat);
            this.llenar_tabla();
            this.limpiar_cajas();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al Eliminar la Materia \n"+e);
        }
       
    }//GEN-LAST:event_btn_borrarActionPerformed

    private void t_materiasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_materiasMouseClicked
        int row = t_materias.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(null, "Seleccione una fila");
        } else {
            cod_mat = Integer.parseInt((String) t_materias.getValueAt(row, 0).toString());
            String nombre = t_materias.getValueAt(row, 1).toString();
            int grado = Integer.parseInt(t_materias.getValueAt(row, 2).toString());
            caja_cod.setText(""+cod_mat);
            caja_nombre.setText(nombre);
            Lista_grados.setSelectedIndex(grado-1);
        }
    }//GEN-LAST:event_t_materiasMouseClicked

    private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarActionPerformed
        try {
            materias m2 = new materias();
            m2.setId(Integer.parseInt(caja_cod.getText().toString()));
            m2.setNombre(caja_nombre.getText().toString());
            int grado = 0;
            String gr = Lista_grados.getSelectedItem().toString();
            switch (gr) {
                case "Segundo":
                    grado = 2;
                    break;
                case "Tercero":
                    grado = 3;
                    break;
                case "Cuarto":
                    grado = 4;
                    break;
                case "Quinto":
                    grado = 5;
                    break;
                case "Sexto":
                    grado = 6;
                    break;
                case "Septimo":
                    grado = 7;
                    break;
                case "Octavo":
                    grado = 8;
                    break;
                case "Noveno":
                    grado = 9;
                    break;
                case "Decimo":
                    grado = 10;
                    break;
                case "Once":
                    grado = 11;
                    break;
            }
            m2.setGrado(grado);
            cm.actualizar(conexion.obtener(), m2,cod_mat);
            this.llenar_tabla();
            this.limpiar_cajas();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error al actualizar Datos..");
        }
    }//GEN-LAST:event_btn_actualizarActionPerformed

    public boolean validar() {
        boolean bandera;
        String codigo = caja_cod.getText();
        String nombre = caja_nombre.getText();
        String grado = this.Lista_grados.getSelectedItem().toString();
        if (!codigo.trim().equals("") && !nombre.trim().equals("")&& grado != "Ninguno") {
            bandera = true;
        } else {
            bandera = false;
            JOptionPane.showMessageDialog(null, "Debe llenar todos los campos");
        }

        return bandera;
    }

    public void guardar() {
        try {
            materias m1 = new materias();
            m1.setId(Integer.parseInt(caja_cod.getText().toString()));
            m1.setNombre(caja_nombre.getText().toString());
            int grado = 0;
            String gr = Lista_grados.getSelectedItem().toString();
            switch (gr) {
                case "Segundo":
                    grado = 2;
                    break;
                case "Tercero":
                    grado = 3;
                    break;
                case "Cuarto":
                    grado = 4;
                    break;
                case "Quinto":
                    grado = 5;
                    break;
                case "Sexto":
                    grado = 6;
                    break;
                case "Septimo":
                    grado = 7;
                    break;
                case "Octavo":
                    grado = 8;
                    break;
                case "Noveno":
                    grado = 9;
                    break;
                case "Decimo":
                    grado = 10;
                    break;
                case "Once":
                    grado = 11;
                    break;
            }
            m1.setGrado(grado);
            cm.guardar(conexion.obtener(), m1);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error al ingresar Datos..");
        }
    }
    
    public void limpiar_cajas(){
        caja_cod.setText("");
        caja_nombre.setText("");
        Lista_grados.setSelectedIndex(0);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Formulario_mat;
    private javax.swing.JComboBox<String> Lista_grados;
    private javax.swing.JButton btn_actualizar;
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_borrar;
    private javax.swing.JTextField caja_cod;
    private javax.swing.JTextField caja_nombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable t_materias;
    // End of variables declaration//GEN-END:variables
}
