/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.BorderLayout;
import java.awt.Color;

/**
 *
 * @author Yessica_Alexandra_Conejo_Munoz
 */
public class Menu_Contenido extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Contenido
     */
    public Menu_Contenido() {
        initComponents();
        setLocationRelativeTo(null);
        
        Bienvenida pag1 = new Bienvenida();
        pag1.setSize(430, 470);
        pag1.setLocation(0,0);
        
        contenido.removeAll();
        contenido.add(pag1,BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panel_contenido = new javax.swing.JPanel();
        Menu_lateral = new javax.swing.JPanel();
        panel_btn_prof = new javax.swing.JPanel();
        label__prof = new javax.swing.JLabel();
        panel_btn_mat = new javax.swing.JPanel();
        label_mat = new javax.swing.JLabel();
        pamel_btn_inicio = new javax.swing.JPanel();
        label_inicio = new javax.swing.JLabel();
        panel_Btn_est = new javax.swing.JPanel();
        label_est = new javax.swing.JLabel();
        panel_btn_cursos = new javax.swing.JPanel();
        label_curso = new javax.swing.JLabel();
        panel_btn_matriculas = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panel_btn_notas = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        label_fup = new javax.swing.JLabel();
        contenido = new javax.swing.JPanel();

        jLabel3.setText("jLabel3");

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Notas");

        panel_contenido.setBackground(new java.awt.Color(255, 255, 255));
        panel_contenido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Menu_lateral.setBackground(new java.awt.Color(1, 72, 128));

        panel_btn_prof.setBackground(new java.awt.Color(2, 180, 230));
        panel_btn_prof.setPreferredSize(new java.awt.Dimension(160, 41));
        panel_btn_prof.setRequestFocusEnabled(false);

        label__prof.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        label__prof.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label__prof.setText("Profesores");
        label__prof.setToolTipText("");
        label__prof.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label__profMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label__profMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label__profMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_btn_profLayout = new javax.swing.GroupLayout(panel_btn_prof);
        panel_btn_prof.setLayout(panel_btn_profLayout);
        panel_btn_profLayout.setHorizontalGroup(
            panel_btn_profLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(panel_btn_profLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_btn_profLayout.createSequentialGroup()
                    .addComponent(label__prof, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panel_btn_profLayout.setVerticalGroup(
            panel_btn_profLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
            .addGroup(panel_btn_profLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(label__prof, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
        );

        panel_btn_mat.setBackground(new java.awt.Color(2, 180, 230));

        label_mat.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        label_mat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_mat.setText("Materias");
        label_mat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_matMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_matMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_matMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_btn_matLayout = new javax.swing.GroupLayout(panel_btn_mat);
        panel_btn_mat.setLayout(panel_btn_matLayout);
        panel_btn_matLayout.setHorizontalGroup(
            panel_btn_matLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(panel_btn_matLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_btn_matLayout.createSequentialGroup()
                    .addComponent(label_mat, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panel_btn_matLayout.setVerticalGroup(
            panel_btn_matLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
            .addGroup(panel_btn_matLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(label_mat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
        );

        pamel_btn_inicio.setBackground(new java.awt.Color(2, 180, 230));

        label_inicio.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        label_inicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_inicio.setText("Inicio");
        label_inicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_inicioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_inicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_inicioMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pamel_btn_inicioLayout = new javax.swing.GroupLayout(pamel_btn_inicio);
        pamel_btn_inicio.setLayout(pamel_btn_inicioLayout);
        pamel_btn_inicioLayout.setHorizontalGroup(
            pamel_btn_inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pamel_btn_inicioLayout.createSequentialGroup()
                .addComponent(label_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pamel_btn_inicioLayout.setVerticalGroup(
            pamel_btn_inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_inicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        panel_Btn_est.setBackground(new java.awt.Color(2, 180, 230));
        panel_Btn_est.setForeground(new java.awt.Color(255, 255, 255));

        label_est.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        label_est.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_est.setText("Estudiantes");
        label_est.setAlignmentY(5.0F);
        label_est.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                label_estFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                label_estFocusLost(evt);
            }
        });
        label_est.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_estMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_estMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_estMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_Btn_estLayout = new javax.swing.GroupLayout(panel_Btn_est);
        panel_Btn_est.setLayout(panel_Btn_estLayout);
        panel_Btn_estLayout.setHorizontalGroup(
            panel_Btn_estLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(panel_Btn_estLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_Btn_estLayout.createSequentialGroup()
                    .addComponent(label_est, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panel_Btn_estLayout.setVerticalGroup(
            panel_Btn_estLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
            .addGroup(panel_Btn_estLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(label_est, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
        );

        panel_btn_cursos.setBackground(new java.awt.Color(2, 180, 230));

        label_curso.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        label_curso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_curso.setText("Cursos");
        label_curso.setPreferredSize(new java.awt.Dimension(170, 40));
        label_curso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_cursoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_cursoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                label_cursoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_btn_cursosLayout = new javax.swing.GroupLayout(panel_btn_cursos);
        panel_btn_cursos.setLayout(panel_btn_cursosLayout);
        panel_btn_cursosLayout.setHorizontalGroup(
            panel_btn_cursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_btn_cursosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label_curso, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_btn_cursosLayout.setVerticalGroup(
            panel_btn_cursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_curso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        panel_btn_matriculas.setBackground(new java.awt.Color(2, 180, 230));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Matriculas");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_btn_matriculasLayout = new javax.swing.GroupLayout(panel_btn_matriculas);
        panel_btn_matriculas.setLayout(panel_btn_matriculasLayout);
        panel_btn_matriculasLayout.setHorizontalGroup(
            panel_btn_matriculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_btn_matriculasLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panel_btn_matriculasLayout.setVerticalGroup(
            panel_btn_matriculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_btn_matriculasLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panel_btn_notas.setBackground(new java.awt.Color(2, 180, 230));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Notas");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_btn_notasLayout = new javax.swing.GroupLayout(panel_btn_notas);
        panel_btn_notas.setLayout(panel_btn_notasLayout);
        panel_btn_notasLayout.setHorizontalGroup(
            panel_btn_notasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panel_btn_notasLayout.setVerticalGroup(
            panel_btn_notasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_btn_notasLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        label_fup.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_fup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/image.png"))); // NOI18N
        label_fup.setToolTipText("Fundacion universitaria de Popayan");

        javax.swing.GroupLayout Menu_lateralLayout = new javax.swing.GroupLayout(Menu_lateral);
        Menu_lateral.setLayout(Menu_lateralLayout);
        Menu_lateralLayout.setHorizontalGroup(
            Menu_lateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Menu_lateralLayout.createSequentialGroup()
                .addGroup(Menu_lateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pamel_btn_inicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Menu_lateralLayout.createSequentialGroup()
                        .addGroup(Menu_lateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panel_btn_notas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panel_btn_matriculas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panel_btn_cursos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panel_btn_mat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panel_Btn_est, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panel_btn_prof, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(label_fup, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        Menu_lateralLayout.setVerticalGroup(
            Menu_lateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Menu_lateralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_fup, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pamel_btn_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_Btn_est, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_btn_prof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_btn_mat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_btn_cursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_btn_matriculas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_btn_notas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        panel_contenido.add(Menu_lateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 470));

        contenido.setBackground(new java.awt.Color(255, 255, 255));
        contenido.setPreferredSize(new java.awt.Dimension(430, 470));

        javax.swing.GroupLayout contenidoLayout = new javax.swing.GroupLayout(contenido);
        contenido.setLayout(contenidoLayout);
        contenidoLayout.setHorizontalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 585, Short.MAX_VALUE)
        );
        contenidoLayout.setVerticalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        panel_contenido.add(contenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 0, 585, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_contenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void label_estFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_label_estFocusLost
        
    }//GEN-LAST:event_label_estFocusLost

    private void label_estFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_label_estFocusGained
        
    }//GEN-LAST:event_label_estFocusGained

    private void label_estMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_estMouseEntered
        this.panel_Btn_est.setBackground(new Color(3,220,185));
    }//GEN-LAST:event_label_estMouseEntered

    private void label_estMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_estMouseExited
        this.panel_Btn_est.setBackground(new Color(2,180,230));
    }//GEN-LAST:event_label_estMouseExited

    private void label__profMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label__profMouseEntered
        this.panel_btn_prof.setBackground(new Color(3,220,185));
    }//GEN-LAST:event_label__profMouseEntered

    private void label__profMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label__profMouseExited
        this.panel_btn_prof.setBackground(new Color(2,180,230));
    }//GEN-LAST:event_label__profMouseExited

    private void label_matMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_matMouseEntered
        this.panel_btn_mat.setBackground(new Color(3,220,185));
    }//GEN-LAST:event_label_matMouseEntered

    private void label_matMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_matMouseExited
        this.panel_btn_mat.setBackground(new Color(2,180,230));
    }//GEN-LAST:event_label_matMouseExited

    private void label_matMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_matMouseClicked
        Crud_materias pag3 = new Crud_materias();
        pag3.setSize(430, 470);
        pag3.setLocation(0,0);
        
        contenido.removeAll();
        contenido.add(pag3,BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
    }//GEN-LAST:event_label_matMouseClicked

    private void label_inicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_inicioMouseEntered
       this.pamel_btn_inicio.setBackground(new Color(3,220,185));
    }//GEN-LAST:event_label_inicioMouseEntered

    private void label_inicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_inicioMouseExited
        this.pamel_btn_inicio.setBackground(new Color(2,180,230));
    }//GEN-LAST:event_label_inicioMouseExited

    private void label_inicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_inicioMouseClicked
        Bienvenida pag1 = new Bienvenida();
        pag1.setSize(430, 470);
        pag1.setLocation(0,0);
        
        contenido.removeAll();
        contenido.add(pag1,BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
    }//GEN-LAST:event_label_inicioMouseClicked

    private void label__profMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label__profMouseClicked
        crud_profesores crp =  new crud_profesores();
        crp.setSize(430, 470);
        crp.setLocation(0, 0);
        
        contenido.removeAll();
        contenido.add(crp,BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
    }//GEN-LAST:event_label__profMouseClicked

    private void label_estMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_estMouseClicked
        crud_estudiantes cre = new crud_estudiantes();
        cre.setSize(430, 470);
        cre.setLocation(0, 0);
        
        contenido.removeAll();
        contenido.add(cre,BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
    }//GEN-LAST:event_label_estMouseClicked

    private void label_cursoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_cursoMouseClicked
        crud_cursos crc = new crud_cursos();
        crc.setSize(430, 470);
        crc.setLocation(0, 0);
        
        contenido.removeAll();
        contenido.add(crc,BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
    }//GEN-LAST:event_label_cursoMouseClicked

    private void label_cursoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_cursoMouseEntered
        this.panel_btn_cursos.setBackground(new Color(3,220,185));
    }//GEN-LAST:event_label_cursoMouseEntered

    private void label_cursoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_cursoMouseExited
        this.panel_btn_cursos.setBackground(new Color(2,180,230));
    }//GEN-LAST:event_label_cursoMouseExited

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        this.panel_btn_matriculas.setBackground(new Color(3,220,185));
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        this.panel_btn_matriculas.setBackground(new Color(2,180,230));
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        this.panel_btn_notas.setBackground(new Color(3,220,185));
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        this.panel_btn_notas.setBackground(new Color(2,180,230));
    }//GEN-LAST:event_jLabel4MouseExited

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        Crud_matricula crmat = new Crud_matricula();
        crmat.setSize(430, 470);
        crmat.setLocation(0, 0);
        
        contenido.removeAll();
        contenido.add(crmat,BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
       crud_notas  cnotas= new crud_notas();
        cnotas.setSize(585, 470);
        cnotas.setLocation(0, 0);
        
        contenido.removeAll();
        contenido.add(cnotas,BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Contenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Contenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Contenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Contenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Contenido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Menu_lateral;
    private javax.swing.JPanel contenido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel label__prof;
    private javax.swing.JLabel label_curso;
    private javax.swing.JLabel label_est;
    private javax.swing.JLabel label_fup;
    private javax.swing.JLabel label_inicio;
    private javax.swing.JLabel label_mat;
    private javax.swing.JPanel pamel_btn_inicio;
    private javax.swing.JPanel panel_Btn_est;
    private javax.swing.JPanel panel_btn_cursos;
    private javax.swing.JPanel panel_btn_mat;
    private javax.swing.JPanel panel_btn_matriculas;
    private javax.swing.JPanel panel_btn_notas;
    private javax.swing.JPanel panel_btn_prof;
    private javax.swing.JPanel panel_contenido;
    // End of variables declaration//GEN-END:variables
}
